<?php
/**
 * Created by PhpStorm.
 * User: alexboyce
 * Date: 4/1/14
 * Time: 1:59 PM
 */

function privatefiles_menu() {
  $menu = array();

  $menu['private/file/%privatefile_hash'] = array(
    'page callback' => 'privatefile_download_link',
    'page arguments' => array(2),
    'access callback' => 'privatefile_access',
    'access arguments' => array('view', 2),
    'type' => MENU_CALLBACK
  );

  $menu['admin/structure/privatefiles'] = array(
    'title' => 'Private Files',
    'description' => t('Manage secured links for privately uploaded files'),
    'page callback' => 'privatefiles_list',
    'access arguments' => array('administer private files'),
    'type' => MENU_NORMAL_ITEM,
    'file' => 'privatefiles.admin.inc'
  );

  $menu['admin/structure/privatefiles/add'] = array(
    'title' => 'Add a private link',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('privatefiles_entity_form'),
    'access callback' => 'privatefile_access',
    'access arguments' => array('create'),
    'type' => MENU_LOCAL_ACTION,
    'file' => 'privatefiles.admin.inc'
  );

  $menu['admin/structure/privatefiles/%privatefile/edit'] = array(
    'title' => 'Edit a link',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('privatefiles_entity_form', 3),
    'access callback' => 'privatefile_access',
    'access arguments' => array('update', 3),
    'type' => MENU_CALLBACK,
    'file' => 'privatefiles.admin.inc'
  );

  $menu['admin/structure/privatefiles/%privatefile/delete'] = array(
    'title' => 'Delete a link',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('privatefiles_delete', 3),
    'access callback' => 'privatefile_access',
    'access arguments' => array('delete', 3),
    'type' => MENU_CALLBACK,
    'file' => 'privatefiles.admin.inc'
  );

  return $menu;
}

function privatefile_hash_load($hash) {
  $hash = urldecode($hash);
  return privatefiles_decode($hash);
}

function privatefile_load($id) {
  return PrivateFileController::load($id);
}

function privatefile_access($op = 'view', PrivateFile $file = NULL, $account = NULL) {
  if (!$account) {
    $account = $GLOBALS['user'];
  }

  if ($account->uid === 1 || user_access('administer private files', $account)) {
    return TRUE;
  }

  if ($op == 'view') {
    if (user_access('bypass private file security', $account)) {
      return TRUE;
    }

    $today = new DateTime();
    dpm($file, 'File');
    dpm((int)($file->expiration_date > $today), 'Expired?');
    if (($file->expiration_date->getTimestamp() > $file->created && $file->expiration_date > $today)
      || $file->expiration_date->getTimestamp() === $file->created) { // this file link hasn't expired or expiration isn't set
      switch ($file->security_level) {
        case PRIVATEFILE_USER_SECURED:
          return in_array($account->uid, $file->users, TRUE);
          break;
        case PRIVATEFILE_ROLE_SECURED:
          foreach (array_keys($account->roles) as $rid) {
            if (in_array($rid, $file->roles, TRUE)) {
              return TRUE;
            }
          }
          return FALSE;
          break;
        case PRIVATEFILE_URL_SECURED:
          return TRUE; // Really not much security involved here, but at least they won't be downloading via this link
          break;
      }
    }
    else {
      return FALSE;
    }
  }
  else {
    return user_access($op.' private files', $account);
  }

  return FALSE;
}

function privatefiles_permission() {
  $perms = array();

  $perms['administer private files'] = array(
    'title' => t('Administer Private Files'),
    'description' => t('Roles with this permission are granted unrestricted access to any private files'),
    'restrict access' => TRUE
  );

  $perms['bypass private file security'] = array(
    'title' => t('Bypass Private File Security'),
    'description' => t('Roles with this permission are granted access to any private file via its URL'),
    'restrict access' => TRUE
  );

  $perms['create private files'] = array(
    'title' => t('Create Private File URL\'s'),
    'description' => t('Roles with this permission can create private URL\'s for files')
  );

  $perms['update private files'] = array(
    'title' => t('Update Private File URL\'s'),
    'description' => t('Roles with this permission can update existing private URL\'s for files')
  );

  $perms['delete private files'] = array(
    'title' => t('Delete Private File URL\'s'),
    'description' => t('Roles with this permission can remove private URL\'s for files
    (the file associated will only be deleted if nothing else is using the file)')
  );

  return $perms;
}

function privatefiles_encode(PrivateFile $file) {
  $salt = variable_get('privatefiles_salt', '');
  $data = $file->id.'|'.$file->fid.'|'.$file->created;
  $secured = mcrypt_encrypt(MCRYPT_BLOWFISH, $salt, $data, MCRYPT_MODE_ECB);
  return base64_encode($secured);
}

function privatefiles_decode($encoded) {
  $salt = variable_get('privatefiles_salt', '');
  $data = base64_decode($encoded);
  $data = mcrypt_decrypt(MCRYPT_BLOWFISH, $salt, $data, MCRYPT_MODE_ECB);
  list($id, $fid, $created) = explode('|', $data);
  $pid = db_select('privatefiles', 'pf')
    ->fields('pf', array('id'))
    ->condition('fid', $fid)
    ->condition('created', $created)
    ->execute()
    ->fetchField();
  if ($pid === $id) {
    return PrivateFileController::load($id);
  }
  return FALSE;
}

function privatefile_download_link(PrivateFile $pfile) {
  $file = file_load($pfile->fid);
  if (!!$file) {
    $schema = file_uri_scheme($file->uri);
    $target = file_uri_target($file->uri);
    file_download($schema, $target);
  }
  return $file->filename;
  drupal_not_found();
}

function privatefiles_file_download($uri) {
  $files = file_load_multiple(FALSE, array('uri' => $uri));
  dpm($files, 'Files to Download');
  if (!!$files && count($files)) {
    foreach ($files as $item) {
      if ($item->uri === $uri) { // Double check, DB's can be case-insensitive
        $file = $item;
        break;
      }
    }

    if (!isset($file)) {
      return NULL;
    }

    $pid = db_select('privatefiles', 'pf')
      ->fields('pf', array('id'))
      ->condition('fid', $file->fid)
      ->execute()->fetchField();

    if (!!$pid) {
      return file_get_content_headers($file);
    }
  }

  return NULL;
}